version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: PlayerBetDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  playerbet-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=PlayerBetDb;Username=postgres;Password=password123;Port=5432

volumes:
  postgres_data:
